### ISSUE TITLE
improve yup schema

### ISSUE THREAD

**Issue by mohamed-sultan** [ruqayy9/backend#3]
instead of
let schema = yup.object().shape({
  email: yup.string().required({"ar":"لا يمكن ترك الايميل فارغ","en":"you can't leave the email blank"}).email({"ar":"ايميل غير صالح", "en": "invalid email"}),
  password:yup.string().min(5,{"ar":" الرجاء ادخال كلمة سر من ٥ احرف على الاقل", "en":"password must be at least 5 characters"}).required({"ar":"لا يمكن ترك كلمة المرور فارغة", "en":"you can't leave the password blank"})
});
write
let schema = yup.object().shape({
  email: yup.string().required({}).email({languages[language].emailRequired}),
  
});

**Comment by ruqayy9** [comment]
Done
